apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: doow0o5pb-nodejs 
  janus-idp.io/tekton: doow0o5pb-nodejs
  backstage.io/kubernetes-id: doow0o5pb-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: doow0o5pb-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml