apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: doow0o5pb-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: doow0o5pb-nodejs 
  name: doow0o5pb-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: doow0o5pb-nodejs 
